# This workflow is intended to run each time a pull request is opened or updated
# It's performing unit and interface tests, and deploying on preview channels

name: Lint, format, test and deploy millions on pull request events
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build
        env:
          REACT_APP_API_URL: "https://testnet-bridge.cosmosmillions.com/"
          REACT_APP_IMPERATOR_API_URL: "https://api-osmosis.imperator.co"
          GENERATE_SOURCEMAP: "false"
          REACT_APP_RPC_LUM: "https://testnet-rpc.cosmosmillions.com/lum/rpc"
          REACT_APP_RPC_ATOM: "https://testnet-rpc.cosmosmillions.com/atom/rpc"
          REACT_APP_FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
          REACT_APP_FIREBASE_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'
          REACT_APP_FIREBASE_DATABASE_URL: '${{ secrets.FIREBASE_DATABASE_URL }}'
          REACT_APP_FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'
          REACT_APP_FIREBASE_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'
          REACT_APP_FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
          REACT_APP_FIREBASE_MEASUREMENT_ID: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'

      - name: Test
        run: yarn test

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          expires: 7d
          projectId: lum-network
          target: lum-network-millions-testnet
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
